INSERT INTO subscriptions (user_id, category_id, name, amount, billing_cycle, next_billing_date, status, source) VALUES
(1, 1, 'Netflix Premium', 19.99, 'monthly', DATE_ADD(CURDATE(), INTERVAL 5 DAY), 'active', 'Seed'),
(1, 2, 'Spotify Family', 15.99, 'monthly', DATE_ADD(CURDATE(), INTERVAL 12 DAY), 'active', 'Seed'),
(1, 3, 'Amazon Prime', 139.00, 'yearly', DATE_ADD(CURDATE(), INTERVAL 45 DAY), 'active', 'Seed'),
(1, 4, 'Gym Membership', 49.99, 'monthly', DATE_ADD(CURDATE(), INTERVAL 2 DAY), 'active', 'Seed'),
(1, 5, 'Dropbox Plus', 11.99, 'monthly', DATE_ADD(CURDATE(), INTERVAL 18 DAY), 'active', 'Seed'),
(1, 1, 'Hulu', 7.99, 'monthly', DATE_ADD(CURDATE(), INTERVAL 22 DAY), 'active', 'Seed'),
(1, 2, 'Apple Music', 10.99, 'monthly', DATE_SUB(CURDATE(), INTERVAL 1 DAY), 'active', 'Seed'),
(1, 3, 'Google One', 19.99, 'yearly', DATE_ADD(CURDATE(), INTERVAL 120 DAY), 'active', 'Seed'),
(1, 4, 'Strava', 59.99, 'yearly', DATE_ADD(CURDATE(), INTERVAL 60 DAY), 'cancelled', 'Seed'),
(1, 5, 'iCloud Storage', 2.99, 'monthly', DATE_ADD(CURDATE(), INTERVAL 8 DAY), 'active', 'Seed'),
(1, 1, 'Disney+', 7.99, 'monthly', DATE_ADD(CURDATE(), INTERVAL 15 DAY), 'active', 'Seed'),
(1, 2, 'YouTube Premium', 11.99, 'monthly', DATE_ADD(CURDATE(), INTERVAL 25 DAY), 'active', 'Seed'),
(1, 3, 'Costco Membership', 60.00, 'yearly', DATE_ADD(CURDATE(), INTERVAL 200 DAY), 'active', 'Seed'),
(1, 4, 'Peloton App', 12.99, 'monthly', DATE_ADD(CURDATE(), INTERVAL 3 DAY), 'cancelled', 'Seed'),
(1, 5, '1Password', 35.88, 'yearly', DATE_ADD(CURDATE(), INTERVAL 90 DAY), 'active', 'Seed'),
(1, 1, 'HBO Max', 14.99, 'monthly', DATE_ADD(CURDATE(), INTERVAL 11 DAY), 'active', 'Seed'),
(1, 2, 'Audible', 14.95, 'monthly', DATE_ADD(CURDATE(), INTERVAL 7 DAY), 'active', 'Seed'),
(1, 3, 'PlayStation Plus', 59.99, 'yearly', DATE_SUB(CURDATE(), INTERVAL 10 DAY), 'active', 'Seed'),
(1, 4, 'MyFitnessPal', 49.99, 'yearly', DATE_ADD(CURDATE(), INTERVAL 150 DAY), 'cancelled', 'Seed'),
(1, 5, 'Notion', 4.00, 'monthly', DATE_ADD(CURDATE(), INTERVAL 19 DAY), 'active', 'Seed');
